[build]
  base = "project"
  command = "npm run build"
  publish = "dist"

[dev]
  base = "project"
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
